version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: solid-js
    versions:
    - 0.23.11
    - 0.24.0
    - 0.24.1
    - 0.24.10
    - 0.24.12
    - 0.24.13
    - 0.24.14
    - 0.24.15
    - 0.24.16
    - 0.24.2
    - 0.24.3
    - 0.24.4
    - 0.24.5
    - 0.24.6
    - 0.24.7
    - 0.24.9
    - 0.25.0
    - 0.25.1
    - 0.26.0
    - 0.26.2
    - 0.26.3
    - 0.26.4
  - dependency-name: esbuild
    versions:
    - 0.11.15
  - dependency-name: svelte-hmr
    versions:
    - 0.14.1
  - dependency-name: "@auth0/auth0-spa-js"
    versions:
    - 1.13.6
    - 1.14.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.2
    - 5.15.3
  - dependency-name: preact
    versions:
    - 10.5.12
    - 10.5.13
  - dependency-name: rollup-plugin-polyfill-node
    versions:
    - 0.5.0
    - 0.6.0
    - 0.6.1
    - 0.6.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
  - dependency-name: "@types/cheerio"
    versions:
    - 0.22.23
    - 0.22.24
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
